version: "3.9"

services:
  back:
    image: conftemplier/back
    container_name: conftemplier-back
    build: ./backend
    restart: always
    ports:
      - 8080:8080
      
  front:
    image: conftemplier/front
    container_name: conftemplier-front
    build:
      context: ./frontend
      dockerfile: /Dockerfile.local
    restart: always
    ports:
      - 80:80
    depends_on:
      - back